version: '3.8'
services:
  postgres-db:
    image: postgres:13
    container_name: gestao-atendimentos-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: atendimentos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: